---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-infra-worker
  namespace: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: default
spec:
  address: http://vault:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-temporal-infra-worker
  namespace: default
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: temporal-infra-worker
    serviceAccount: temporal-infra-worker
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: temporal-cloud-secret
  namespace: default
spec:
  vaultAuthRef: vault-auth-temporal-infra-worker
  mount: secret
  type: kv-v1
  path: temporal-cloud
  destination:
    name: temporal-cloud-creds
    create: true
  refreshAfter: "1h"
  rolloutRestartTargets:
    - kind: Deployment
      name: temporal-infra-worker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-infra-worker-config
  namespace: default
data:
  TEMPORAL_HOST_URL: "us-west-2.aws.api.temporal.io:7233"
  TEMPORAL_NAMESPACE: "neil-vault-api-keys-c9f141c8.sdvdw"
  TEMPORAL_TASK_QUEUE: "provision-infra"
  TF_VAR_prefix: "neil"
  ENCRYPT_PAYLOADS: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: temporal-infra-worker
   namespace: default
   labels:
      app: temporal-infra-worker
spec:
   selector:
      matchLabels:
         app: temporal-infra-worker
   replicas: 1
   template:
      metadata:
         labels:
            app: temporal-infra-worker
      spec:
         serviceAccountName: temporal-infra-worker
         containers:
            - name: temporal-infra-worker
              image: eklhad/temporal-infra-worker:latest
              env:
                - name: TEMPORAL_HOST_URL
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TEMPORAL_HOST_URL
                - name: TEMPORAL_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TEMPORAL_NAMESPACE
                - name: TEMPORAL_TASK_QUEUE
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TEMPORAL_TASK_QUEUE
                - name: TF_VAR_prefix
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TF_VAR_prefix
                - name: ENCRYPT_PAYLOADS
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: ENCRYPT_PAYLOADS
                - name: TEMPORAL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: temporal-api-key
                      key: TEMPORAL_API_KEY
              resources:
                limits:
                  cpu: "0.5"
                  memory: "512Mi"
                requests:
                  cpu: "0.2"
                  memory: "256Mi"
